# Cleaning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset.csv")
df.head()

,system.index,aspect,bare.coverfraction,bedrock_depth_mean,bio01,bio02,bio03,bio04,bio05,bio06,...,area_herbaceous_cover_cropland_lag1yr,area_irrigated_cropland_lag1yr,area_forest_lag1yr,area_shrubland_lag1yr,area_grassland_lag1yr,area_sparse_veg_lag1yr,area_wetlands_lag1yr,area_built_up_lag1yr,area_bare_lag1yr,area_open_water_lag1yr
0,00000000000000000000,183.604181,0.030682,200.0,26.594812,8.476023,71.257726,10.962520,32.860071,21.050554,...,0.012450,0.013340,1914.920283,0.074933,0.129867,0.012451,0.370666,10.853481,0.000889,0.096916
1,00000000000000000003,185.425880,0.065276,200.0,26.614498,9.175814,72.536327,10.815446,33.530253,20.964695,...,0.026725,0.015206,1901.506549,0.175087,0.116440,0.008889,0.597385,24.045927,0.000889,0.314707
2,00000000000000000004,190.578224,0.062759,200.0,26.675871,8.706088,71.878645,10.865571,33.136983,21.112895,...,0.027564,0.016895,1903.457450,0.129953,0.092564,0.010671,0.376095,22.010989,0.000889,0.276497
3,00000000000000000005,186.927523,0.067935,200.0,26.631666,8.904753,72.341121,10.857358,33.288415,21.069153,...,0.029338,0.017781,1903.708462,0.130687,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721
4,00000000000000000006,186.927523,0.067935,200.0,26.631666,8.904753,72.341121,10.857358,33.288415,21.069153,...,0.029338,0.017781,1903.708462,0.130687,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721

In [3]:
len(df)

1818

Removing all variables listed as "n" in data dictionary

In [4]:
cols = [
    "system.index", "bare.coverfraction", "bio01", "bio02", "bio03", "bio04", "bio05", "bio06", "bio07", "bio08", "bio09", "bio10", "bio11", 
    "bulk", "cisi", "clay", "crops.coverfraction", "day", "f_prim", "fertility_class", "gHM", "gdp_mean", "gdp_var", "grass.coverfraction", 
    "hlth_ds", "latitud", "longitd", "m_prim", "month", "n_exmnd", "occurrence", "pH", "recurrence", "sand", "schl_nm", "sh_nexm", "sh_post", 
    "shrub.coverfraction", "sm_post", "soilCarbon", "texture_class", "tree.coverfraction", "urban.coverfraction", "water.permanent.coverfraction", 
    "water.seasonal.coverfraction", "pop_date", "pop_year", "schl_yr", "pop_year_lag1yr", "schl_mo", "schl_yrmo", "swe_mean", "ter_date", 
    "ter_month", "ter_year", "ter_yrmo", "ter_yrmo_lag1mo", "swe_mean_lag1mo", "ter_yrmo_lag2mo", "swe_mean_lag2mo", "ter_yrmo_lag3mo", 
    "swe_mean_lag3mo", "ter_yrmo_lag4mo", "swe_mean_lag4mo", "ter_yrmo_lag5mo", "swe_mean_lag5mo", "ter_yrmo_lag6mo", "swe_mean_lag6mo", 
    "ter_yrmo_lag7mo", "swe_mean_lag7mo", "ter_yrmo_lag8mo", "swe_mean_lag8mo", "ter_yrmo_lag9mo", "swe_mean_lag9mo", "ter_yrmo_lag10mo", 
    "swe_mean_lag10mo", "ter_yrmo_lag11mo", "swe_mean_lag11mo", "ter_yrmo_lag12mo", "swe_mean_lag12mo", "SR_B1_mean", "SR_B2_mean", "SR_B3_mean", 
    "SR_B4_mean", "SR_B5_mean", "SR_B7_mean", "ST_B10_mean", "im_date", "im_month", "im_year", "im_yrmo", "lsat_yrmo_lag1mo", "sr_b1_mean_lag1mo", 
    "sr_b2_mean_lag1mo", "sr_b3_mean_lag1mo", "sr_b4_mean_lag1mo", "sr_b5_mean_lag1mo", "sr_b7_mean_lag1mo", "st_b10_mean_lag1mo", "lsat_yrmo_lag2mo", 
    "sr_b1_mean_lag2mo", "sr_b2_mean_lag2mo", "sr_b3_mean_lag2mo", "sr_b4_mean_lag2mo", "sr_b5_mean_lag2mo", "sr_b7_mean_lag2mo", "st_b10_mean_lag2mo", 
    "lsat_yrmo_lag3mo", "sr_b1_mean_lag3mo", "sr_b2_mean_lag3mo", "sr_b3_mean_lag3mo", "sr_b4_mean_lag3mo", "sr_b5_mean_lag3mo", "sr_b7_mean_lag3mo", 
    "st_b10_mean_lag3mo", "lsat_yrmo_lag4mo", "sr_b1_mean_lag4mo", "sr_b2_mean_lag4mo", "sr_b3_mean_lag4mo", "sr_b4_mean_lag4mo", "sr_b5_mean_lag4mo", 
    "sr_b7_mean_lag4mo", "st_b10_mean_lag4mo", "lsat_yrmo_lag5mo", "sr_b1_mean_lag5mo", "sr_b2_mean_lag5mo", "sr_b3_mean_lag5mo", "sr_b4_mean_lag5mo", 
    "sr_b5_mean_lag5mo", "sr_b7_mean_lag5mo", "st_b10_mean_lag5mo", "lsat_yrmo_lag6mo", "sr_b1_mean_lag6mo", "sr_b2_mean_lag6mo", "sr_b3_mean_lag6mo", 
    "sr_b4_mean_lag6mo", "sr_b5_mean_lag6mo", "sr_b7_mean_lag6mo", "st_b10_mean_lag6mo", "lsat_yrmo_lag7mo", "sr_b1_mean_lag7mo", "sr_b2_mean_lag7mo", 
    "sr_b3_mean_lag7mo", "sr_b4_mean_lag7mo", "sr_b5_mean_lag7mo", "sr_b7_mean_lag7mo", "st_b10_mean_lag7mo", "lsat_yrmo_lag8mo", "sr_b1_mean_lag8mo", 
    "sr_b2_mean_lag8mo", "sr_b3_mean_lag8mo", "sr_b4_mean_lag8mo", "sr_b5_mean_lag8mo", "sr_b7_mean_lag8mo", "st_b10_mean_lag8mo", "lsat_yrmo_lag9mo", 
    "sr_b1_mean_lag9mo", "sr_b2_mean_lag9mo", "sr_b3_mean_lag9mo", "sr_b4_mean_lag9mo", "sr_b5_mean_lag9mo", "sr_b7_mean_lag9mo", "st_b10_mean_lag9mo", 
    "lsat_yrmo_lag10mo", "sr_b1_mean_lag10mo", "sr_b2_mean_lag10mo", "sr_b3_mean_lag10mo", "sr_b4_mean_lag10mo", "sr_b5_mean_lag10mo", "sr_b7_mean_lag10mo", 
    "st_b10_mean_lag10mo", "lsat_yrmo_lag11mo", "sr_b1_mean_lag11mo", "sr_b2_mean_lag11mo", "sr_b3_mean_lag11mo", "sr_b4_mean_lag11mo", "sr_b5_mean_lag11mo", 
    "sr_b7_mean_lag11mo", "st_b10_mean_lag11mo", "lsat_yrmo_lag12mo", "sr_b1_mean_lag12mo", "sr_b2_mean_lag12mo", "sr_b3_mean_lag12mo", "sr_b4_mean_lag12mo", 
    "sr_b5_mean_lag12mo", "sr_b7_mean_lag12mo", "st_b10_mean_lag12mo", "lulc_year", "schol_yr", "lulc_yr_lag1yr"
]

In [5]:
df = df.drop(columns=cols)
df.head()

,aspect,bedrock_depth_mean,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,...,area_herbaceous_cover_cropland_lag1yr,area_irrigated_cropland_lag1yr,area_forest_lag1yr,area_shrubland_lag1yr,area_grassland_lag1yr,area_sparse_veg_lag1yr,area_wetlands_lag1yr,area_built_up_lag1yr,area_bare_lag1yr,area_open_water_lag1yr
0,183.604181,200.0,1508.830955,280.060468,21.733899,57.115762,646.825496,120.533794,337.455792,317.999699,...,0.012450,0.013340,1914.920283,0.074933,0.129867,0.012451,0.370666,10.853481,0.000889,0.096916
1,185.425880,200.0,1377.345726,241.037560,16.313812,57.442422,585.446491,93.790261,325.758583,328.468667,...,0.026725,0.015206,1901.506549,0.175087,0.116440,0.008889,0.597385,24.045927,0.000889,0.314707
2,190.578224,200.0,1446.334404,261.036755,19.465539,56.627543,615.037975,109.811994,328.340045,321.447973,...,0.027564,0.016895,1903.457450,0.129953,0.092564,0.010671,0.376095,22.010989,0.000889,0.276497
3,186.927523,200.0,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.029338,0.017781,1903.708462,0.130687,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721
4,186.927523,200.0,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.029338,0.017781,1903.708462,0.130687,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721

Filtering all post 2019

In [6]:
filtered_df = df[df['year'] < 2019]
filtered_df

,aspect,bedrock_depth_mean,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,...,area_herbaceous_cover_cropland_lag1yr,area_irrigated_cropland_lag1yr,area_forest_lag1yr,area_shrubland_lag1yr,area_grassland_lag1yr,area_sparse_veg_lag1yr,area_wetlands_lag1yr,area_built_up_lag1yr,area_bare_lag1yr,area_open_water_lag1yr
0,183.604181,200.000000,1508.830955,280.060468,21.733899,57.115762,646.825496,120.533794,337.455792,317.999699,...,0.012450,0.013340,1914.920283,0.074933,0.129867,0.012451,0.370666,10.853481,0.000889,0.096916
1,185.425880,200.000000,1377.345726,241.037560,16.313812,57.442422,585.446491,93.790261,325.758583,328.468667,...,0.026725,0.015206,1901.506549,0.175087,0.116440,0.008889,0.597385,24.045927,0.000889,0.314707
2,190.578224,200.000000,1446.334404,261.036755,19.465539,56.627543,615.037975,109.811994,328.340045,321.447973,...,0.027564,0.016895,1903.457450,0.129953,0.092564,0.010671,0.376095,22.010989,0.000889,0.276497
3,186.927523,200.000000,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.029338,0.017781,1903.708462,0.130687,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721
4,186.927523,200.000000,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.029338,0.017781,1903.708462,0.130687,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1781,175.894180,199.994981,1394.855386,265.084019,12.526002,63.791606,626.972542,73.165778,259.101799,622.791588,...,0.004432,NaN,1853.798308,24.490661,0.013294,0.185405,4.564108,13.912753,0.021273,7.009784
1782,172.548618,199.978153,1525.434371,285.713904,13.252617,64.114136,689.668872,76.351853,285.847580,681.678590,...,0.002660,0.003547,1865.813736,11.467410,0.006207,0.014183,0.201890,29.890035,NaN,0.001774
1783,179.351368,199.999975,1395.601557,252.328301,14.692797,57.583724,569.940314,89.073386,301.566096,520.616641,...,0.011541,0.032855,1715.238925,5.123801,0.003551,0.563824,38.775236,17.261871,0.073709,55.075660
1784,165.346038,199.990415,1478.862700,278.517084,12.898370,63.998466,665.964303,74.576893,277.598148,664.910081,...,0.001773,0.002660,1873.723878,11.662481,0.004432,0.008864,0.154243,15.891669,NaN,0.001774
1785,157.802970,199.998396,1477.090242,278.778649,14.780218,60.770202,625.221172,87.795951,296.454463,573.660467,...,0.034636,0.014207,1793.228220,7.600094,0.035519,0.554845,37.394434,28.095651,0.059497,43.986953

Joining the lag data and extra variables

In [7]:
lag1 = pd.read_csv("1yrlag.csv")
lag1.head()

     gdp_mean schol_d
0  16000000.0   pam 1
1  29400000.0  pam 12
2  25600000.0  pam 13
3  25300000.0  pam 14
4  25300000.0  pam 15

In [8]:
merged_df = pd.merge(filtered_df, lag1, on='schol_d', how='left')
merged_df.head()

,aspect,bedrock_depth_mean,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,...,area_irrigated_cropland_lag1yr,area_forest_lag1yr,area_shrubland_lag1yr,area_grassland_lag1yr,area_sparse_veg_lag1yr,area_wetlands_lag1yr,area_built_up_lag1yr,area_bare_lag1yr,area_open_water_lag1yr,gdp_mean
0,183.604181,200.0,1508.830955,280.060468,21.733899,57.115762,646.825496,120.533794,337.455792,317.999699,...,0.013340,1914.920283,0.074933,0.129867,0.012451,0.370666,10.853481,0.000889,0.096916,16000000.0
1,185.425880,200.0,1377.345726,241.037560,16.313812,57.442422,585.446491,93.790261,325.758583,328.468667,...,0.015206,1901.506549,0.175087,0.116440,0.008889,0.597385,24.045927,0.000889,0.314707,29400000.0
2,190.578224,200.0,1446.334404,261.036755,19.465539,56.627543,615.037975,109.811994,328.340045,321.447973,...,0.016895,1903.457450,0.129953,0.092564,0.010671,0.376095,22.010989,0.000889,0.276497,25600000.0
3,186.927523,200.0,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.017781,1903.708462,0.130687,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,25300000.0
4,186.927523,200.0,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.017781,1903.708462,0.130687,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,25300000.0

In [9]:
lag2 = pd.read_csv("extra_data.csv")
lag2.head()

  schol_d  total_pop_lag3yr  gdp_mean_lag3yr  gdp_mean_lag5yr
0   pam 1     105437.180646     1.636735e+07     1.647667e+07
1  pam 12     140894.190245     2.985771e+07     2.989439e+07
2  pam 13     156083.530521     2.600184e+07     2.605977e+07
3  pam 14     130071.696107     2.575529e+07     2.582808e+07
4  pam 15     130071.696107     2.575529e+07     2.582808e+07

In [10]:
final_df = pd.merge(merged_df, lag2, on='schol_d', how='left')
final_df.head()

,aspect,bedrock_depth_mean,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,...,area_grassland_lag1yr,area_sparse_veg_lag1yr,area_wetlands_lag1yr,area_built_up_lag1yr,area_bare_lag1yr,area_open_water_lag1yr,gdp_mean,total_pop_lag3yr,gdp_mean_lag3yr,gdp_mean_lag5yr
0,183.604181,200.0,1508.830955,280.060468,21.733899,57.115762,646.825496,120.533794,337.455792,317.999699,...,0.129867,0.012451,0.370666,10.853481,0.000889,0.096916,16000000.0,105437.180646,1.636735e+07,1.647667e+07
1,185.425880,200.0,1377.345726,241.037560,16.313812,57.442422,585.446491,93.790261,325.758583,328.468667,...,0.116440,0.008889,0.597385,24.045927,0.000889,0.314707,29400000.0,140894.190245,2.985771e+07,2.989439e+07
2,190.578224,200.0,1446.334404,261.036755,19.465539,56.627543,615.037975,109.811994,328.340045,321.447973,...,0.092564,0.010671,0.376095,22.010989,0.000889,0.276497,25600000.0,156083.530521,2.600184e+07,2.605977e+07
3,186.927523,200.0,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,25300000.0,130071.696107,2.575529e+07,2.582808e+07
4,186.927523,200.0,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,25300000.0,130071.696107,2.575529e+07,2.582808e+07

Splitting into different specie

In [11]:
final_df

,aspect,bedrock_depth_mean,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,...,area_grassland_lag1yr,area_sparse_veg_lag1yr,area_wetlands_lag1yr,area_built_up_lag1yr,area_bare_lag1yr,area_open_water_lag1yr,gdp_mean,total_pop_lag3yr,gdp_mean_lag3yr,gdp_mean_lag5yr
0,183.604181,200.000000,1508.830955,280.060468,21.733899,57.115762,646.825496,120.533794,337.455792,317.999699,...,0.129867,0.012451,0.370666,10.853481,0.000889,0.096916,1.600000e+07,105437.180646,1.636735e+07,1.647667e+07
1,185.425880,200.000000,1377.345726,241.037560,16.313812,57.442422,585.446491,93.790261,325.758583,328.468667,...,0.116440,0.008889,0.597385,24.045927,0.000889,0.314707,2.940000e+07,140894.190245,2.985771e+07,2.989439e+07
2,190.578224,200.000000,1446.334404,261.036755,19.465539,56.627543,615.037975,109.811994,328.340045,321.447973,...,0.092564,0.010671,0.376095,22.010989,0.000889,0.276497,2.560000e+07,156083.530521,2.600184e+07,2.605977e+07
3,186.927523,200.000000,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,2.530000e+07,130071.696107,2.575529e+07,2.582808e+07
4,186.927523,200.000000,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,2.530000e+07,130071.696107,2.575529e+07,2.582808e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1781,175.894180,199.994981,1394.855386,265.084019,12.526002,63.791606,626.972542,73.165778,259.101799,622.791588,...,0.013294,0.185405,4.564108,13.912753,0.021273,7.009784,5.384014e+06,96657.256388,4.686037e+06,4.002429e+06
1782,172.548618,199.978153,1525.434371,285.713904,13.252617,64.114136,689.668872,76.351853,285.847580,681.678590,...,0.006207,0.014183,0.201890,29.890035,NaN,0.001774,2.290000e+07,259012.837724,1.991745e+07,1.679662e+07
1783,179.351368,199.999975,1395.601557,252.328301,14.692797,57.583724,569.940314,89.073386,301.566096,520.616641,...,0.003551,0.563824,38.775236,17.261871,0.073709,55.075660,1.730000e+07,145999.885540,1.508205e+07,1.281859e+07
1784,165.346038,199.990415,1478.862700,278.517084,12.898370,63.998466,665.964303,74.576893,277.598148,664.910081,...,0.004432,0.008864,0.154243,15.891669,NaN,0.001774,1.310000e+07,143062.583056,1.141841e+07,9.680133e+06
1785,157.802970,199.998396,1477.090242,278.778649,14.780218,60.770202,625.221172,87.795951,296.454463,573.660467,...,0.035519,0.554845,37.394434,28.095651,0.059497,43.986953,1.860000e+07,255482.880573,1.620272e+07,1.371823e+07

In [20]:
sh = final_df[final_df["sh_prev"] >= 0]
sh

,aspect,bedrock_depth_mean,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,...,area_grassland_lag1yr,area_sparse_veg_lag1yr,area_wetlands_lag1yr,area_built_up_lag1yr,area_bare_lag1yr,area_open_water_lag1yr,gdp_mean,total_pop_lag3yr,gdp_mean_lag3yr,gdp_mean_lag5yr
0,183.604181,200.000000,1508.830955,280.060468,21.733899,57.115762,646.825496,120.533794,337.455792,317.999699,...,0.129867,0.012451,0.370666,10.853481,0.000889,0.096916,1.600000e+07,105437.180646,1.636735e+07,1.647667e+07
1,185.425880,200.000000,1377.345726,241.037560,16.313812,57.442422,585.446491,93.790261,325.758583,328.468667,...,0.116440,0.008889,0.597385,24.045927,0.000889,0.314707,2.940000e+07,140894.190245,2.985771e+07,2.989439e+07
2,190.578224,200.000000,1446.334404,261.036755,19.465539,56.627543,615.037975,109.811994,328.340045,321.447973,...,0.092564,0.010671,0.376095,22.010989,0.000889,0.276497,2.560000e+07,156083.530521,2.600184e+07,2.605977e+07
3,186.927523,200.000000,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,2.530000e+07,130071.696107,2.575529e+07,2.582808e+07
4,186.927523,200.000000,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,2.530000e+07,130071.696107,2.575529e+07,2.582808e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1781,175.894180,199.994981,1394.855386,265.084019,12.526002,63.791606,626.972542,73.165778,259.101799,622.791588,...,0.013294,0.185405,4.564108,13.912753,0.021273,7.009784,5.384014e+06,96657.256388,4.686037e+06,4.002429e+06
1782,172.548618,199.978153,1525.434371,285.713904,13.252617,64.114136,689.668872,76.351853,285.847580,681.678590,...,0.006207,0.014183,0.201890,29.890035,NaN,0.001774,2.290000e+07,259012.837724,1.991745e+07,1.679662e+07
1783,179.351368,199.999975,1395.601557,252.328301,14.692797,57.583724,569.940314,89.073386,301.566096,520.616641,...,0.003551,0.563824,38.775236,17.261871,0.073709,55.075660,1.730000e+07,145999.885540,1.508205e+07,1.281859e+07
1784,165.346038,199.990415,1478.862700,278.517084,12.898370,63.998466,665.964303,74.576893,277.598148,664.910081,...,0.004432,0.008864,0.154243,15.891669,NaN,0.001774,1.310000e+07,143062.583056,1.141841e+07,9.680133e+06
1785,157.802970,199.998396,1477.090242,278.778649,14.780218,60.770202,625.221172,87.795951,296.454463,573.660467,...,0.035519,0.554845,37.394434,28.095651,0.059497,43.986953,1.860000e+07,255482.880573,1.620272e+07,1.371823e+07

In [22]:
sm = final_df[final_df["sm_prev"] >= 0]
sm

,aspect,bedrock_depth_mean,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,...,area_grassland_lag1yr,area_sparse_veg_lag1yr,area_wetlands_lag1yr,area_built_up_lag1yr,area_bare_lag1yr,area_open_water_lag1yr,gdp_mean,total_pop_lag3yr,gdp_mean_lag3yr,gdp_mean_lag5yr
0,183.604181,200.000000,1508.830955,280.060468,21.733899,57.115762,646.825496,120.533794,337.455792,317.999699,...,0.129867,0.012451,0.370666,10.853481,0.000889,0.096916,1.600000e+07,105437.180646,1.636735e+07,1.647667e+07
1,185.425880,200.000000,1377.345726,241.037560,16.313812,57.442422,585.446491,93.790261,325.758583,328.468667,...,0.116440,0.008889,0.597385,24.045927,0.000889,0.314707,2.940000e+07,140894.190245,2.985771e+07,2.989439e+07
2,190.578224,200.000000,1446.334404,261.036755,19.465539,56.627543,615.037975,109.811994,328.340045,321.447973,...,0.092564,0.010671,0.376095,22.010989,0.000889,0.276497,2.560000e+07,156083.530521,2.600184e+07,2.605977e+07
3,186.927523,200.000000,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,2.530000e+07,130071.696107,2.575529e+07,2.582808e+07
4,186.927523,200.000000,1426.579422,254.018940,18.599338,56.953311,606.025688,103.754191,327.599493,330.564783,...,0.087157,0.011558,0.573416,21.549089,0.003556,0.314721,2.530000e+07,130071.696107,2.575529e+07,2.582808e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1781,175.894180,199.994981,1394.855386,265.084019,12.526002,63.791606,626.972542,73.165778,259.101799,622.791588,...,0.013294,0.185405,4.564108,13.912753,0.021273,7.009784,5.384014e+06,96657.256388,4.686037e+06,4.002429e+06
1782,172.548618,199.978153,1525.434371,285.713904,13.252617,64.114136,689.668872,76.351853,285.847580,681.678590,...,0.006207,0.014183,0.201890,29.890035,NaN,0.001774,2.290000e+07,259012.837724,1.991745e+07,1.679662e+07
1783,179.351368,199.999975,1395.601557,252.328301,14.692797,57.583724,569.940314,89.073386,301.566096,520.616641,...,0.003551,0.563824,38.775236,17.261871,0.073709,55.075660,1.730000e+07,145999.885540,1.508205e+07,1.281859e+07
1784,165.346038,199.990415,1478.862700,278.517084,12.898370,63.998466,665.964303,74.576893,277.598148,664.910081,...,0.004432,0.008864,0.154243,15.891669,NaN,0.001774,1.310000e+07,143062.583056,1.141841e+07,9.680133e+06
1785,157.802970,199.998396,1477.090242,278.778649,14.780218,60.770202,625.221172,87.795951,296.454463,573.660467,...,0.035519,0.554845,37.394434,28.095651,0.059497,43.986953,1.860000e+07,255482.880573,1.620272e+07,1.371823e+07

In [14]:
sx = final_df[(final_df["sh_prev"] == 0) & (final_df["sm_prev"] == 0)]
sx

,aspect,bedrock_depth_mean,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,...,area_grassland_lag1yr,area_sparse_veg_lag1yr,area_wetlands_lag1yr,area_built_up_lag1yr,area_bare_lag1yr,area_open_water_lag1yr,gdp_mean,total_pop_lag3yr,gdp_mean_lag3yr,gdp_mean_lag5yr
393,96.944957,199.976453,2010.573289,535.136385,31.000949,79.479545,1036.002593,171.478154,335.817769,349.977138,...,0.241296,0.065890,24.684020,24.070383,0.040959,1193.148744,20100000.0,93799.773946,1.940698e+07,1.860653e+07
394,113.283715,199.984027,1985.101927,518.174160,31.000776,77.565651,1009.333983,170.271842,336.467079,353.344486,...,0.281355,0.124277,24.065405,28.424243,0.051718,883.135963,22600000.0,141904.827550,2.179835e+07,2.091429e+07
395,149.019797,199.995753,2035.584354,504.008452,35.869812,74.446815,1005.218551,187.918113,342.000119,342.596953,...,0.184420,0.113090,26.133857,14.855910,0.026713,416.283862,22000000.0,107826.157487,2.048624e+07,1.942358e+07
396,170.041958,199.998740,1923.082563,446.426776,33.591796,67.654517,901.705970,172.972854,346.897052,372.683875,...,0.194941,0.171515,16.052061,18.852482,0.035607,246.825093,26100000.0,183253.605658,2.516354e+07,2.415699e+07
397,126.852252,199.987360,2000.609219,512.640229,32.275859,76.086342,1004.315160,174.322014,339.487236,356.570178,...,0.290457,0.133545,25.515255,26.393804,0.049861,773.395932,22900000.0,141570.679402,2.208552e+07,2.119310e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1712,179.466736,199.998980,1100.184662,192.283647,10.235407,59.715498,425.640104,50.418731,254.027723,410.053785,...,0.225961,0.083290,1.123479,82.989654,NaN,4.350584,129000000.0,628556.191529,1.109048e+08,1.059568e+08
1716,172.737318,200.000000,1092.498590,196.862702,10.036799,60.651114,432.746763,49.365654,247.795449,421.172801,...,0.215635,0.034545,1.355084,63.297280,NaN,1.883218,94200000.0,496727.469683,8.098892e+07,7.735140e+07
1730,199.436208,199.997960,1090.966699,213.641614,7.779403,62.752082,446.643235,52.249371,251.627239,428.850278,...,0.065558,0.387010,12.953654,21.394519,1.526524,7.664661,23100000.0,145075.163271,2.004519e+07,1.949565e+07
1745,172.765938,199.576918,1059.948861,170.469593,9.302233,61.189506,425.295759,45.065473,249.446643,354.639312,...,0.047899,0.065823,0.925375,14.493787,NaN,4.345020,14100000.0,104692.216005,1.226457e+07,1.191813e+07
1774,181.530372,200.000000,1362.819546,241.768411,14.530745,56.476037,548.507967,88.137830,302.847758,501.336022,...,0.024856,0.253027,0.536187,17.889484,NaN,0.032464,20400000.0,160416.776417,1.775972e+07,1.508025e+07

In [23]:
sh.to_csv('sh.csv', index=False)
sm.to_csv('sm.csv', index=False)